name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy Docker Container on EC2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~
          sudo apt-get install libpq-dev python-dev
          rm -rf fastapi-complete
          git clone https://github.com/testifyhelper/fastapi-complete.git
          cd fastapi-complete
          docker-compose down
          docker-compose up -d